MTAR_PATTERN_PCRE_SRC_DIR		:= src/module/pattern/pcre
MTAR_PATTERN_PCRE_BUILD_DIR		:= ${BUILD_DIR}/module/pattern/pcre
MTAR_PATTERN_PCRE_DEPEND_DIR	:= ${DEPEND_DIR}/module/pattern/pcre

MTAR_PATTERN_PCRE_SRC_FILES		:= $(sort $(shell test -d ${MTAR_PATTERN_PCRE_SRC_DIR} && find ${MTAR_PATTERN_PCRE_SRC_DIR} -name '*.c'))
MTAR_PATTERN_PCRE_HEAD_FILES	:= $(sort $(shell test -d ${MTAR_PATTERN_PCRE_SRC_DIR} && find ${MTAR_PATTERN_PCRE_SRC_DIR} -name '*.h'))
MTAR_PATTERN_PCRE_OBJ_FILES		:= $(sort $(patsubst src/%.c,${BUILD_DIR}/%.o,${MTAR_PATTERN_PCRE_SRC_FILES}))
MTAR_PATTERN_PCRE_DEP_FILES		:= $(sort $(shell test -d ${MTAR_PATTERN_PCRE_DEPEND_DIR} && find ${MTAR_PATTERN_PCRE_DEPEND_DIR} -name '*.d'))

MTAR_PATTERN_PCRE_BIN			:= lib/libpattern-pcre.so
MTAR_PATTERN_PCRE_CFLAG			:= -I. -fPIC -fvisibility=hidden
MTAR_PATTERN_PCRE_LD			:= -shared -lpcre

MTAR_PATTERN_PCRE_LIB			:=

BIN_SYMS						+= MTAR_PATTERN_PCRE
