MTAR_EXCLUDE_PCRE_SRC_DIR		:= src/module/exclude/pcre
MTAR_EXCLUDE_PCRE_BUILD_DIR		:= ${BUILD_DIR}/module/exclude/pcre
MTAR_EXCLUDE_PCRE_DEPEND_DIR	:= ${DEPEND_DIR}/module/exclude/pcre

MTAR_EXCLUDE_PCRE_SRC_FILES		:= $(sort $(shell test -d ${MTAR_EXCLUDE_PCRE_SRC_DIR} && find ${MTAR_EXCLUDE_PCRE_SRC_DIR} -name '*.c'))
MTAR_EXCLUDE_PCRE_HEAD_FILES	:= $(sort $(shell test -d ${MTAR_EXCLUDE_PCRE_SRC_DIR} && find ${MTAR_EXCLUDE_PCRE_SRC_DIR} -name '*.h'))
MTAR_EXCLUDE_PCRE_OBJ_FILES		:= $(sort $(patsubst src/%.c,${BUILD_DIR}/%.o,${MTAR_EXCLUDE_PCRE_SRC_FILES}))
MTAR_EXCLUDE_PCRE_DEP_FILES		:= $(sort $(shell test -d ${MTAR_EXCLUDE_PCRE_DEPEND_DIR} && find ${MTAR_EXCLUDE_PCRE_DEPEND_DIR} -name '*.d'))

MTAR_EXCLUDE_PCRE_BIN			:= lib/libexclude-pcre.so
MTAR_EXCLUDE_PCRE_CFLAG			:= -I. -fPIC -fvisibility=hidden
MTAR_EXCLUDE_PCRE_LD			:= -shared -lpcre

MTAR_EXCLUDE_PCRE_LIB			:=

BIN_SYMS						+= MTAR_EXCLUDE_PCRE
